### ISSUE TITLE
Readme OpenAI API Key 

### ISSUE THREAD

**Issue by acdc-digital** [get-convex/convex-ai-chat-langchain#1]
Hey guys-
Just a quick fyi, as it took me a few minutes to notice while setting up. I just copy/pasted the readme text, which reads, "OPEN_API_KEY set to an [OpenAI](https://platform.openai.com/) API key (should start with sk-)" but it should be 'OPENAI_API_KEY' in convex environment variables dashboard. Anyways, just letting you know. Cheers.

**Comment by Ninoambaraa** [comment]
finally :) ,  i got the answer

**Comment by xixixao** [comment]
Thanks fixed.
